# Import Libraries

In [1]:
# Data Manipulation
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Settings
pd.set_option('display.max_columns', None)
sns.set_style("whitegrid")

# Load Datasets

In [2]:
# Load datasets

marketing_df = pd.read_csv("Marketing.csv")

customers_df = pd.read_csv("olist_customers_dataset.csv")

retail_df = pd.read_excel("Online Retail.xlsx")

print("Marketing Shape:", marketing_df.shape)
print("Customers Shape:", customers_df.shape)
print("Retail Shape:", retail_df.shape)

Marketing Shape: (308, 11)
Customers Shape: (99441, 5)
Retail Shape: (541909, 8)

# Basic Data Inspection

In [3]:
datasets = {
    "Marketing": marketing_df,
    "Customers": customers_df,
    "Retail": retail_df
}

for name, df in datasets.items():
    print(f"\n{name} Dataset")
    print("="*50)

    print("\nFirst 5 Rows")
    display(df.head())

    print("\nInfo")
    print(df.info())

    print("\nMissing Values")
    print(df.isnull().sum())

    print("\nDuplicate Rows")
    print(df.duplicated().sum())

Marketing Dataset
==================================================

First 5 Rows

,id,c_date,campaign_name,category,campaign_id,impressions,mark_spent,clicks,leads,orders,revenue
0,1,2021-02-01,facebook_tier1,social,349043,148263,7307.37,1210,13,1,4981.0
1,2,2021-02-01,facebOOK_tier2,social,348934,220688,16300.20,1640,48,3,14962.0
2,3,2021-02-01,google_hot,search,89459845,22850,5221.60,457,9,1,7981.0
3,4,2021-02-01,google_wide,search,127823,147038,6037.00,1196,24,1,2114.0
4,5,2021-02-01,youtube_blogger,influencer,10934,225800,29962.20,2258,49,10,84490.0

Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308 entries, 0 to 307
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             308 non-null    int64
 1   c_date         308 non-null    object
 2   campaign_name  308 non-null    object
 3   category       308 non-null    object
 4   campaign_id    308 non-null    int64
 5   impressions    308 non-null    int64
 6   mark_spent     308 non-null    float64
 7   clicks         308 non-null    int64
 8   leads          308 non-null    int64
 9   orders         308 non-null    int64
 10  revenue        308 non-null    float64
dtypes: float64(2), int64(6), object(3)
memory usage: 26.6+ KB
None

Missing Values
id               0
c_date           0
campaign_name    0
category         0
campaign_id      0
impressions      0
mark_spent       0
clicks           0
leads            0
orders           0
revenue          0
dtype: int64

Duplicate Rows
0

Customers Dataset
==================================================

First 5 Rows

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB
None

Missing Values
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

Duplicate Rows
0

Retail Dataset
==================================================

First 5 Rows

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB
None

Missing Values
InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

Duplicate Rows
5268

# Handle Missing UTM Parameters

In [4]:
utm_cols = ['utm_source', 'utm_medium', 'utm_campaign']

for col in utm_cols:
    if col in marketing_df.columns:
        marketing_df[col] = marketing_df[col].fillna('Unknown')

print("UTM Missing Values Handled")

UTM Missing Values Handled

# Standardize Timestamp Formats

Marketing Dataset

In [5]:
if 'c_date' in marketing_df.columns:
    marketing_df['c_date'] = pd.to_datetime(
        marketing_df['c_date'],
        errors='coerce',
        utc=True
    )

marketing_df['c_date'].head()

0   2021-02-01 00:00:00+00:00
1   2021-02-01 00:00:00+00:00
2   2021-02-01 00:00:00+00:00
3   2021-02-01 00:00:00+00:00
4   2021-02-01 00:00:00+00:00
Name: c_date, dtype: datetime64[ns, UTC]

Online Retail Dataset

In [6]:
retail_df['InvoiceDate'] = pd.to_datetime(
    retail_df['InvoiceDate'],
    errors='coerce',
    utc=True
)

retail_df['InvoiceDate'].head()

0   2010-12-01 08:26:00+00:00
1   2010-12-01 08:26:00+00:00
2   2010-12-01 08:26:00+00:00
3   2010-12-01 08:26:00+00:00
4   2010-12-01 08:26:00+00:00
Name: InvoiceDate, dtype: datetime64[ns, UTC]

# Remove Duplicate User IDs

Customers Dataset

In [7]:
print("Original Shape:", customers_df.shape)

customers_df = customers_df.drop_duplicates(
    subset=['customer_unique_id']
)

print("After Deduplication:", customers_df.shape)

Original Shape: (99441, 5)
After Deduplication: (96096, 5)

# Marketing Dataset

In [8]:
if 'id' in marketing_df.columns:
    marketing_df = marketing_df.drop_duplicates(subset=['id'])